name: Deploy Solution
on: 
  workflow_dispatch: 

  push:
    branches:
      - main
      - develop
      - 'release/**'
jobs:
  package-unreal-engine-game:
    runs-on: self-hosted
    steps: 
      - name: Download Source
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Build Project
        run: | 
          cd scripts
          ls
          ./buildProject.bat  "..\RPGGame\RPGGame.uproject" "..\RPGGame\Builds"

      - name: Zip Project
        run: | 
          ls
          powershell Compress-Archive ./RPGGame/Builds/Windows/* windowsBuild.zip

      - name: Download Butler
        run: | 
          curl -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default
          powershell Expand-Archive butler.zip
        
      - name: Publish the build Folder
        run: |
          ./butler/butler.exe push RPGGame/Builds/Windows matioma/unrealrpg-tst:win-64
        env: 
          BUTLER_API_KEY: ${{ secrets.ITCH_IO }}
