name: Deploy Solution
on: 
  workflow_dispatch: 

  push:
    branches:
      - main
      - develop
      - 'release/**'
jobs:
  test:
    runs-on: self-hosted
    steps: 
      - name: Download Source
        uses: actions/checkout@v3
        with:
          lfs: 'true'